import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "WSYLH | وسيلة",
  description: "Generated by create next app",
};

const cairo = Cairo({ subsets: ["arabic"], variable: "--font-cairo" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${cairo.variable}`}>{children}</body>
    </html>
  );
}
